import ClothingImg from '../../public/images/expenses/clothing.png';
import TravelImg from '../../public/images/expenses/travel.png';
import TransportImg from '../../public/images/expenses/transport.png';
import GasImg from '../../public/images/expenses/gas.png';
import MealsImg from '../../public/images/expenses/meals.png';
import InsuranceImg from '../../public/images/expenses/insurance.png';
import PaymentImg from '../../public/payment.png';
import MoreImg from '../../public/More.png';

import {
  LayoutDashboard,
  HandCoins,
  Landmark,
  CircleDollarSign,
  Newspaper,
  ListTree,
  Wallet,
  ClipboardPen,
} from 'lucide-react';
import { FaUser } from 'react-icons/fa';
import { FcLineChart, FcPackage } from 'react-icons/fc';

export const menuConfig = {
  admin: [
    {
      href: '/dashboard',
      label: 'Dashboard',
      icon: LayoutDashboard,
    },
    {
      href: '/orders',
      label: 'Orders',
      icon: HandCoins,
      badge: 6,
    },
    {
      href: '/products',
      label: 'Products',
      icon: FcPackage,
      subItems: [
        { href: '/products/categories', label: 'Categories' },
        { href: '/products/new', label: 'New Product' },
      ],
    },
    {
      href: '/customers',
      label: 'Customers',
      icon: FaUser,
    },
    {
      href: '/analytics',
      label: 'Analytics',
      icon: FcLineChart,
      subItems: [
        { href: '/analytics/sales', label: 'Sales' },
        { href: '/analytics/traffic', label: 'Traffic' },
      ],
    },
  ],
  seller: [
    {
      href: '/',
      label: 'Dashboard',
      icon: LayoutDashboard,
    },
    {
      href: '/orders',
      label: 'Orders',
      icon: HandCoins,
      badge: 3,
    },
    {
      href: '/products',
      label: 'Products',
      icon: FcPackage,
      subItems: [
        { href: '/products/inventory', label: 'Inventory' },
        { href: '/products/new', label: 'New Product' },
      ],
    },
  ],
  customer: [
    {
      href: '/dashboard',
      label: 'Dashboard',
      icon: LayoutDashboard,
    },
    {
      href: '/incomes',
      label: 'Incomes',
      icon: Wallet,
    },
    {
      href: '/expenses',
      label: 'Expenses',
      icon: HandCoins,
    },
    {
      href: '/categories',
      label: 'Categories',
      icon: ListTree,
    },
    {
      href: '/rules',
      label: 'Rules',
      icon: ClipboardPen,
    },
    {
      href: '/deductions',
      label: 'Deductions',
      icon: Landmark,
      subItems: [
        { href: '/deductions/2024', label: '2024' },
        { href: '/deductions/2023', label: '2023' },
        { href: '/deductions/2022', label: '2022' },
      ],
    },
    {
      href: '/tax-file',
      label: 'Tax File',
      icon: Newspaper,
    },
    {
      href: '/write-offs',
      label: 'Write-offs',
      icon: CircleDollarSign,
    },
  ],
};

export const expense_categories = [
  {
    id: 1,
    imageSrc: ClothingImg,
    category: 'Rent',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 2,
    imageSrc: TravelImg,
    category: 'Utilities',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 3,
    imageSrc: TransportImg,
    category: 'Office Supplies',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 4,
    imageSrc: GasImg,
    category: 'Furniture and Equipment',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 5,
    imageSrc: MealsImg,
    category: 'Maintenance and Repairs',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 6,
    imageSrc: InsuranceImg,
    category: 'Computer Hardware',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 7,
    imageSrc: PaymentImg,
    category: 'Software Subscriptions',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 8,
    imageSrc: MoreImg,
    category: 'Internet and Phone Expenses',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 9,
    imageSrc: MoreImg,
    category: 'Cloud Storage and Services',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 10,
    imageSrc: MoreImg,
    category: 'Website Hosting',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 11,
    imageSrc: MoreImg,
    category: 'Accounting and Legal Fees',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 12,
    imageSrc: MoreImg,
    category: 'Consulting Services',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 13,
    imageSrc: MoreImg,
    category: 'Professional Memberships',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 14,
    imageSrc: MoreImg,
    category: 'Training and Certification',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 15,
    imageSrc: MoreImg,
    category: 'Online Advertising',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 16,
    imageSrc: MoreImg,
    category: 'Print Materials',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 17,
    imageSrc: MoreImg,
    category: 'Social Media Marketing',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 18,
    imageSrc: MoreImg,
    category: 'Business Cards',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 19,
    imageSrc: MoreImg,
    category: 'Marketing Software',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 20,
    imageSrc: MoreImg,
    category: 'Business Travel Expenses',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 21,
    imageSrc: MoreImg,
    category: 'Vehicle Expenses',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 22,
    imageSrc: MoreImg,
    category: 'Fuel',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 23,
    imageSrc: MoreImg,
    category: 'Parking and Tolls',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 24,
    imageSrc: MoreImg,
    category: 'Public Transportation',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 25,
    imageSrc: MoreImg,
    category: 'Salaries and Wages',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 26,
    imageSrc: MoreImg,
    category: 'Benefits',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 27,
    imageSrc: MoreImg,
    category: 'Recruitment Costs',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 28,
    imageSrc: MoreImg,
    category: 'Training Programs',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 29,
    imageSrc: MoreImg,
    category: 'Others',
    totalItemByCategory: 0,
    amount: 0,
  },
];
export const income_categories = [
  {
    id: 1,
    imageSrc: ClothingImg,
    category: 'Salary/Wages',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 2,
    imageSrc: TravelImg,
    category: 'Bonuses',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 3,
    imageSrc: TransportImg,
    category: 'Overtime Pay',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 4,
    imageSrc: GasImg,
    category: 'Holiday Pay',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 5,
    imageSrc: MealsImg,
    category: 'Freelance Earnings',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 6,
    imageSrc: InsuranceImg,
    category: 'Business Profits',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 7,
    imageSrc: PaymentImg,
    category: 'Interest',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 8,
    imageSrc: MoreImg,
    category: 'Dividends',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 9,
    imageSrc: MoreImg,
    category: 'Rental Income',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 10,
    imageSrc: MoreImg,
    category: 'Capital Gains',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 11,
    imageSrc: MoreImg,
    category: 'Unemployment Benefits',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 12,
    imageSrc: MoreImg,
    category: 'Pension',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 13,
    imageSrc: MoreImg,
    category: 'Sick Pay',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 14,
    imageSrc: MoreImg,
    category: 'Parental Leave Pay',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 15,
    imageSrc: MoreImg,
    category: 'Child Benefits',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 16,
    imageSrc: MoreImg,
    category: 'Inheritance',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 17,
    imageSrc: MoreImg,
    category: 'Scholarships/Grants',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 18,
    imageSrc: MoreImg,
    category: 'Prizes/Awards',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 19,
    imageSrc: MoreImg,
    category: 'Alimony/Child Support',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 20,
    imageSrc: MoreImg,
    category: 'Gifts Over Tax-Free Limits',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 21,
    imageSrc: MoreImg,
    category: 'Honorariums',
    totalItemByCategory: 0,
    amount: 0,
  },
  {
    id: 22,
    imageSrc: MoreImg,
    category: 'Side Hustle Income',
    totalItemByCategory: 0,
    amount: 0,
  },
];

export const expenseWriteOffs = [
  {
    id: 1,
    title: 'Business meals',
    quantity: 18,
    amount: '$200',
  },
  {
    id: 2,
    title: 'Travels',
    quantity: 1,
    amount: '$6',
  },
  {
    id: 3,
    title: 'Clothing',
    quantity: 1,
    amount: '$3',
  },
  {
    id: 4,
    title: 'Supplies',
    quantity: 1,
    amount: '$12',
  },
  {
    id: 5,
    title: 'Payment',
    quantity: 1,
    amount: '$5',
  },
  {
    id: 6,
    title: 'Gas',
    quantity: 1,
    amount: '$2',
  },
  {
    id: 7,
    title: 'Review your deductions',
    quantity: 0,
    amount: 46,
  },
  {
    id: 8,
    title: 'Questions answered',
    quantity: 0,
    amount: '8 out of 9',
  },
  {
    id: 9,
    title: 'Potential saving total from 46 write-offs',
    quantity: 0,
    amount: '$2,086',
  },
];

export const summaryWriteOffs = [
  {
    id: 1,
    title: 'Review your deductions',
    quantity: 46,
    amount: 0,
  },
  {
    id: 2,
    title: 'Questions answered',
    quantity: '8 out of 9',
    amount: 0,
  },
  {
    id: 3,
    title: 'Potential saving total from 46 write-offs',
    quantity: 1,
    amount: '$2,086',
  },
];
export const transactions = [
  {
    description: 'Uber One Sydney AU Aus',
    category: 'Transport',
    type: 'Business',
    amount: 100.55,
  },
  {
    description: 'foodpanda.com Dhaka BGD card',
    category: 'Meals',
    type: "Don't know",
    amount: 30.65,
  },
  {
    description: 'International Transaction Fee',
    category: 'Travel',
    type: 'Personal',
    amount: 30.65,
  },
  {
    description: 'Uber One Sydney AU Aus',
    category: 'Transport',
    type: 'Personal',
    amount: 30.65,
  },
  {
    description: 'BFC Dhaka BGD',
    category: 'Meals',
    type: 'Business',
    amount: 30.65,
  },
];

export const categories = [
  // { label: 'Supplies', amount: 0, image: '/Supplies.svg' },
  { label: 'Rent', amount: 0, image: ClothingImg },
  { label: 'Utilities', amount: 0, image: TravelImg },
  { label: 'Office Supplies', amount: 0, image: TransportImg },
  { label: 'Furniture and Equipment', amount: 0, image: GasImg },
  { label: 'Maintenance and Repairs', amount: 0, image: MealsImg },
  { label: 'Computer Hardware', amount: 0, image: InsuranceImg },
  { label: 'Software Subscriptions', amount: 0, image: PaymentImg },
  { label: 'Internet and Phone Expenses', amount: 0, image: MoreImg },
  { label: 'Cloud Storage and Services', amount: 0, image: MoreImg },
  { label: 'Website Hosting', amount: 0, image: MoreImg },
  { label: 'Accounting and Legal Fees', amount: 0, image: MoreImg },
  { label: 'Consulting Services', amount: 0, image: MoreImg },
  { label: 'Professional Memberships', amount: 0, image: MoreImg },
  { label: 'Training and Certification', amount: 0, image: MoreImg },
  { label: 'Online Advertising', amount: 0, image: MoreImg },
  { label: 'Print Materials', amount: 0, image: MoreImg },
  { label: 'Social Media Marketing', amount: 0, image: MoreImg },
  { label: 'Business Cards', amount: 0, image: MoreImg },
  { label: 'Marketing Software', amount: 0, image: MoreImg },
  { label: 'Business Travel Expenses', amount: 0, image: MoreImg },
  { label: 'Vehicle Expenses', amount: 0, image: MoreImg },
  { label: 'Fuel', amount: 0, image: MoreImg },
  { label: 'Parking and Tolls', amount: 0, image: MoreImg },
  { label: 'Public Transportation', amount: 0, image: MoreImg },
  { label: 'Salaries and Wages', amount: 0, image: MoreImg },
  { label: 'Benefits', amount: 0, image: MoreImg },
  { label: 'Recruitment Costs', amount: 0, image: MoreImg },
  { label: 'Training Programs', amount: 0, image: MoreImg },
  { label: 'Others', amount: 0, image: MoreImg },
];
export const predefinedCategories = [
  {
    id: 1,
    name: 'Office and Workspace',
    items: [
      { name: 'Rent', amount: 0, original_amount: 0 },
      { name: 'Utilities', amount: 0, original_amount: 0 },
      { name: 'Office Supplies', amount: 0, original_amount: 0 },
      { name: 'Furniture and Equipment', amount: 0, original_amount: 0 },
      { name: 'Maintenance and Repairs', amount: 0, original_amount: 0 },
    ],
    total_amount: 0,
    total_original_amount: 0,
  },
  {
    id: 2,
    name: 'Technology and Communication',
    items: [
      { name: 'Computer Hardware', amount: 0, original_amount: 0 },
      { name: 'Software Subscriptions', amount: 0, original_amount: 0 },
      { name: 'Internet and Phone Expenses', amount: 0, original_amount: 0 },
      { name: 'Cloud Storage and Services', amount: 0, original_amount: 0 },
      { name: 'Website Hosting', amount: 0, original_amount: 0 },
    ],
    total_amount: 0,
    total_original_amount: 0,
  },
  {
    id: 3,
    name: 'Professional Services',
    items: [
      { name: 'Accounting and Legal Fees', amount: 0, original_amount: 0 },
      { name: 'Consulting Services', amount: 0, original_amount: 0 },
      { name: 'Professional Memberships', amount: 0, original_amount: 0 },
      { name: 'Training and Certification', amount: 0, original_amount: 0 },
    ],
    total_amount: 0,
    total_original_amount: 0,
  },
  {
    id: 4,
    name: 'Marketing and Advertising',
    items: [
      { name: 'Online Advertising', amount: 0, original_amount: 0 },
      { name: 'Print Materials', amount: 0, original_amount: 0 },
      { name: 'Social Media Marketing', amount: 0, original_amount: 0 },
      { name: 'Business Cards', amount: 0, original_amount: 0 },
      { name: 'Marketing Software', amount: 0, original_amount: 0 },
    ],
    total_amount: 0,
    total_original_amount: 0,
  },
  {
    id: 5,
    name: 'Travel and Transportation',
    items: [
      { name: 'Business Meal Expenses', amount: 0, original_amount: 0 },
      { name: 'Vehicle Expenses', amount: 0, original_amount: 0 },
      { name: 'Fuel', amount: 0, original_amount: 0 },
      { name: 'Parking and Tolls', amount: 0, original_amount: 0 },
      { name: 'Public Transportation', amount: 0, original_amount: 0 },
    ],
    total_amount: 0,
    total_original_amount: 0,
  },
  {
    id: 6,
    name: 'Employee-Related Expenses',
    items: [
      { name: 'Salaries and Wages', amount: 0, original_amount: 0 },
      { name: 'Benefits', amount: 0, original_amount: 0 },
      { name: 'Recruitment Costs', amount: 0, original_amount: 0 },
      { name: 'Training Programs', amount: 0, original_amount: 0 },
    ],
    total_amount: 0,
    total_original_amount: 0,
  },
  {
    id: 7,
    name: 'Custom Category Expenses',
    items: [{ name: 'N/A', amount: 0, original_amount: 0 }],
    total_amount: 0,
    total_original_amount: 0,
  },
];
